### ISSUE TITLE
Error, "No package.xml found", when I try to save static resources and/or apex classes using Sublime 3 w/ Lightning package

### ISSUE THREAD

**Issue by vinicius5581** [heroku/force#192] opened 2015-07-27 09:05 UTC
I am working on a Salesforce project using Sublime Text 3 as my IDE.  

I have a salesforce developer account. I have a pc running windows 8. 

I've installed "[force cli][1]" to my computer and to Sublime Text 3 I installed the package "[lighting][2]".

I have my project root at C:\\Users\\myuser\\Desktop\\salesforce\ . 

On the"Lighting" menu that opens when I right click on a file within Sublime Text 3 side bar files browser, I can login to my org and fetch aura bundles, classes and static resources, however, I can only deploy aura components. When I save a change on a class or a static resource I get the following error:

>Failures - 1

>"package.xml", line 0: Error No package.xml found

On the console I get the following when saving a change on a class file:

>Type: ApexClass
>Item: AwesomeProductController
>Running force fetch -t ApexClass -n AwesomeProductController -unpack
[WinError 267] The directory name is invalid: 'C:\\Users\\myuser\\Desktop\\salesforce\\metadata\\classes\\AwesomeProductController.cls\\*.*'
Running force push -f=C:\Users\myuser\Desktop\salesforce\metadata\classes\AwesomeProductController.cls

On the console I get the following when saving a change on a Static Resource file:

>[WinError 267] The directory name is invalid: 'C:\\Users\\myuser\\Desktop\\salesforce\\metadata\\staticresources\\coreStyles.resource\\*.*'
>Running force push -f=C:\Users\myuser\Desktop\salesforce\metadata\staticresources\coreStyles.resource

Any ideas?

  [1]: https://force-cli.herokuapp.com
  [2]: https://github.com/dcarroll/sublime-lightning

**Comment by MaxwellVolz** [comment] 2015-07-27 16:43
I was having the same problem you described and fixed it by uninstalling my current version of Ruby and reinstalling Sublime and it's associated packages.

Good Luck!

**Comment by vinicius5581** [comment] 2015-07-28 17:14
Thanks @MaxwellVolz! I had to dig a little more dipper, but is working now. 

I got it working after doing the follow steps:

Uninstalling Java JDK, Ruby, Node, force cli and Sublime and deleting all left over files from those program (C:/users/myuser/AppData/ & C:/Program Data).
Installed Sublime, force cli and lightning package to sublime.
It should work and if not, you might want to consider restarting your computer. After that you can install Java JDK, Ruby and Node again.

Even though I still don't know what the problem is, this will certainly make it work.

I hope this helps.

**Comment by dcarroll** [comment] 2015-08-05 15:33
Well, that's a lot of uninstall/re-install. Can't reproduce, so I'm closing this.

**Closed by dcarroll** 2015-08-05 15:33 UTC

**Comment by boxfoot** [comment] 2015-08-13 04:35
I'm having the same problem.  Would love to avoid uninstall/re-install if possible.  Is there any debug info I could provide that would help debug this?

**Comment by boxfoot** [comment] 2015-08-13 04:40
```bash

$ force push -t StaticResource -n MyResource
Validating and deploying push...
Deploying now...

Failures - 1
ERROR with package.xml, line 0
 No package.xml found
The deployment took 20.5441751s to run.

$ force import -v

Failures - 1
package.xml: No package.xml found

Successes - 0
Imported from c:\Users\boxfoot\git\my-project\metadata
```

metadata\package.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types><members>MyResource</members><name>StaticResource</name></types>
  <version>33.0</version>
</Package>
```

**Comment by dcarroll** [comment] 2015-08-13 16:30
Import using packages is super picky.  Make sure there are no other files,
hidden or otherwise, being zipped (within the metadata folder).  If there
is any other file at the root of the archive you get this unhelpful
response from the server.

On Wed, Aug 12, 2015 at 9:40 PM, Benj <notifications@github.com> wrote:

> $ force push -t StaticResource -n MyResource
> Validating and deploying push...
> Deploying now...
>
> Failures - 1
> ERROR with package.xml, line 0
>  No package.xml found
> The deployment took 20.5441751s to run.
>
> $ force import -v
>
> Failures - 1
> package.xml: No package.xml found
>
> Successes - 0
> Imported from c:\Users\boxfoot\git\my-project\metadata
>
> metadata\package.xml:
>
> <?xml version="1.0" encoding="UTF-8"?>
> <Package xmlns="http://soap.sforce.com/2006/04/metadata">
>   <types><members>MyResource</members><name>StaticResource</name></types>
>   <version>33.0</version>
> </Package>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/192#issuecomment-130533521>.
>



-- 
Thanks,
Dave

**Comment by boxfoot** [comment] 2015-08-18 21:42
Updating to the latest binary seems to have solved the problem.  Thanks for the help!
