### ISSUE TITLE
ConnectEx tcp: The semaphore timeout period has expired - does CLI work over proxy?

### ISSUE THREAD

**Issue by collymitch** [heroku/force#51] opened 2014-01-09 13:11 UTC
I'm using the Windows EXE from https://force-cli.heroku.com.

I login to either dev or live, copy the link to Chrome (because it doesn't seem to work in firefox) - page on chrome tells me auth worked ok then after 30 seconds or so the cmd line updates with an error:

```
ERROR: Get https://login.salesforce.com/id/[...id removed...]/[...id removed...]
: dial tcp 204.14.233.101:443: ConnectEx tcp: The semaphore timeout period has expired.
```

We have an internet proxy here - is there any way of telling CLI about this proxy or is this a different issue?

Thanks.

**Comment by SravanPodapati** [comment] 2015-02-16 09:19
Hi Guys, 

Any update on this issue. I am still having issues with login on windows. 

Thanks 
Sravan

**Comment by jarwady** [comment] 2016-02-16 19:58
Hey Everyone,

This is a very important issue and I hope it will be addressed soon.  Many of us DEVs that work for larger companies with well-established security models are dealing with a proxy and there is currently no intuitive (or any) way to deal with this.  Like the comments above state, the issue is not with getting my browser to display the "you may close this tab" screen, but rather that the command line hangs afterwards and eventually times out.  

I have tried using set HTTP_PROXY=etc... in the command prompt.  I have also tried going to the Windows Control Panel and creating environment variables.  I've tried different variations, user:password@proxy.com:80 , etc.  No matter what I try I get the same results.  

If this tool is not compatible with a proxy then it needs to state that clearly.  If it is compatible, then it should also state that clearly with the correct steps to make it work.  

This tool is a vital part of my workflow and I need to know once and for all if I can use it, or if I have to find something else.  Please reply and advise.

**Comment by cwarden** [comment] 2016-02-16 20:06
@jarwady, have you tried testing master?  Proxy support was added in #254.

**Comment by jarwady** [comment] 2016-02-17 02:29
Outstanding @cwarden !  Sorry that I did not know that.  

I will read your comments from #254 and post again once I get it working or if I have more questions.  

Thank you.

**Comment by jarwady** [comment] 2016-02-17 13:04
@cwarden I have added the variables as instructed in #254 but unfortunately it has not changed my situation.  Here are the exact values of the two system variables I've added in the control panel.  There are two conventions in use: one is that "proxy.com" is replaced with my actual proxy; and two is that I'm using "http://" for both variable values as instructed in some research I found (however I also tried "https://" and it made no difference).

Variable Name: HTTP_PROXY
Variable Value: http://proxy.com:80

Variable Name: HTTPS_PROXY
Variable Value: http://proxy.com:80

Please let me know if there is anything else I need to do or add/change.  Thanks.

**Comment by cwarden** [comment] 2016-02-17 17:00
@jarwady, did you build from source?  The last release doesn't have the changes in #254.

I just tested on Windows, and it seems to be working correctly.

![force-proxy-windows](https://cloud.githubusercontent.com/assets/387035/13117451/d7c85c56-d554-11e5-85a7-d61d405fa4d8.gif)

**Comment by jarwady** [comment] 2016-02-17 19:51
@cwarden : Thanks for the great visuals!  I did not build it, but rather downloaded force.exe from the heroku site.  To build it, I assume I need to have Google Go installed, and then run the appropriate command?

**Comment by dcarroll** [comment] 2016-02-17 20:06
I will publish a new release and then you will be able to download a new
binary.


On Wed, Feb 17, 2016 at 11:51 AM, jarwady <notifications@github.com> wrote:

> @cwarden <https://github.com/cwarden> : Thanks for the great visuals! I
> did not build it, but rather downloaded force.exe from the heroku site. To
> build it, I assume I need to have Google Go installed, and then run the
> appropriate command?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/51#issuecomment-185374369>.
>



-- 
Thanks,
Dave

**Comment by jarwady** [comment] 2016-02-17 22:36
@dcarroll : Thanks!!

**Closed** 2017-03-30 20:03 UTC
